### PR TITLE
Continue if keytar fails

### LINKED ISSUE #58: Deal with Keytar Failure
For passwords, we're using Keytar - a C++ module that enables integration with the current operating system. However, if Keytar fails to load for whatever reason, the app is basically unusable.

**Expected behavior**: If Keytar fails to load, the user can still use the app - he/she is just presented with the blog's normal login screen.

### PR DESCRIPTION
**Pull request by dbhowell**
* Wraps the keytar require in a try/catch. If it throws then return false, otherwise return the module.
* On setPassword return false if keytar fails
* On getPassword return null if keytar fails

(fixes #58)

### CODE REVIEW

**Comment by bnookala** [comment]
@dbhowell Thanks for this! Can you add a basic set of unit tests for `require-keytar.js`?

**Comment by dbhowell** [comment]
Will do. I'm still trying to get the tests to run on my Windows machine.

**Comment by felixrieseberg** [comment]
@dbhowell I got them running on my machine - hit me up on Slack, I'm happy to walk you through it (or, alternatively, to fix some of the issues) :+1:

**Comment by dbhowell** [comment]
* unit test added
* rebased
* squashed

Thanks @felixrieseberg for taking the time to help me sort out my environment setup.

**Comment by felixrieseberg** [comment]
Thanks a bunch for the contribution!

**Pull request merged**
