### PR TITLE
Use intelligent offline check

### PR DESCRIPTION
**Pull request by bnookala**
Does away with the navigator.isOnline check and uses a more intelligent reachability check to the update server, and breaks up the checkForUpdates method to be a bit more readable for corner cases.

### CODE REVIEW

**Comment by bnookala** [comment]
@felixrieseberg do you have any idea why the prior 3 commits would also appear in the PR?

**Comment by kennethlimcp** [comment]
@bnookala you should be able to do something like `git rebase master -i` to sync up with the latest code

**Comment by felixrieseberg** [comment]
@kennethlimcp is right, but I can also just squash while merging (thanks, :octocat:!). As soon as tests pass, I'll hit that button, code looks good 👍

**Comment by kennethlimcp** [comment]
definitely love the squash feature :D

**Pull request merged**
